server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html/public; # Laravelの公開ディレクトリを指定

    location / {
        try_files $uri $uri/ /index.php?$query_string; # Laravelのルーティングを有効にする
    }

    location ~ \.php$ {
        try_files $uri = 404; # PHPファイルが存在しない場合は404エラーを返す
        fastcgi_split_path_info ^(.+\.php)(/.+)$; # PATH_INFOを正しく処理するための設定
        fastcgi_pass app:9000; # docker-composeのサービス名とポート
        fastcgi_index index.php; # デフォルトのPHPファイル
        include fastcgi_params; # FastCGIのパラメータを読み込む
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # PHPファイルのパスを指定
        fastcgi_param PATH_INFO $fastcgi_path_info; # PATH_INFOを設定
    }
}